### ISSUE TITLE
Скрыть firebase credentials.

### ISSUE THREAD

**Issue by beeloon** [Shramkoweb/crwn-clothing#26]
Здравствуй :)

Советую скрыть данные в твоем firebase конфиге, и добавить их через переменные окружения(.env).
Так как хорошей практикой является сокрытия подобных данных.

Например, вместо этого:
```js
const config = {
  apiKey: 'AIzaSyBid9mxl4bYGvqKnHiV8A0E......',
};
```
Записывать так:
```js
const config = {
  apiKey: process.env.REACT_APP_API_KEY,
};
```
В файле, **.env** нужно перед каждой переменной писать REACT_APP, так как эта фича уже присутсвует в [create-react-app](https://create-react-app.dev/docs/adding-custom-environment-variables/).

**Comment by Shramkoweb** [comment]
@beeloon привет, спасибо. Да это отличная идея.

**Comment by Shramkoweb** [comment]
done
